### ISSUE TITLE
Documentation on usage for large projects

### ISSUE THREAD

**Issue by Hvanderwilk** [vimeo/psalm#4973]
I've been trying to configure Psalm in the CI for a large project, around 9M LOC. While I was quite content with the results on even the highest analysis level in terms of issues found, due to performance reasons I might be unable to use it. A full project run takes around 20 minutes, 16G+ of memory and the result cache size is 13G. The bright side is that when the cache was used the analysis was relatively very fast, sometimes around a minute.

Some issues here mention similar sized projects, but not with enough information to get a decent setup myself. Some documentation on how to successfully get this up and running and what to expect in terms of performance would help a lot.

My next attempt would probably be to virtually split the project up into multiple analyses. If I happen to find a working setup, I'm happy to contribute to this documentation. Until then I hope you have some suggestions 🙂 

Background on how I'm running it: `./vendor/bin/psalm --memory-limit=20G --long-progress`. If I'm correct this means max number of threads is used and caching is on by default.

Configuration (removed some project related names/directories):
```xml
<?xml version="1.0"?>
<psalm
        errorLevel="8"
        cacheDirectory="cache/psalm"
        allowStringToStandInForClass="true"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="https://getpsalm.org/schema/config"
        xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
    <projectFiles>
        <directory name="src/*/code" />
        <ignoreFiles>
            <directory name="vendor" />
        </ignoreFiles>
    </projectFiles>
```

**Comment by orklah** [comment]
If you use git, I think the 1 minute long analysis was due to the diff functionnality rather than just the cache.

The diff functionnality checks what changed since last time to analyse only relevant files. It's pretty fast when there is few modifications.

I'd suggest trying without the cache actually. On my project, it uses so much ram and has to write so much I can't even run a full analysis when cache is enabled. Maybe you would have a similar issue.

I'd advise against running only part of your project unless there is no concrete dependancies (i.e. there is an API between the two). Some functionnalities of Psalm will need to have your full project to run correctly (for example, unused code detection)

**Comment by orklah** [comment]
You can also add reportInfo=false in your psalm config. It's a flag I added to get rid of extra time spent by Psalm to handle issues below your errorLevel (to be able to report them as info if needed). It should be the most efficient on high errorLevel when most of the issues are at lower level (which seems to be your case here)

Please report here if you notice an effect with that flag, it was pretty efficient when doing my tests some time ago but I don't use it often and I lack datas on that.

**Comment by weirdan** [comment]
If you're using cache make sure you're restoring modification times after git clone in CI. Here's how we do it (Github actions workflow):
```yaml
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # infinite depth is required for mtime restore to work correctly
          fetch-depth: 0

      # mtime needs to be restored for Psalm cache to work correctly
      - name: Restore mtimes
        uses: weirdan/git-restore-mtime-action@master

      # the way cache keys are set up will always cause a cache miss
      # but will restore the cache generated during the previous run
      # based on partial match
      - name: Retrieve Psalm's cache
        uses: actions/cache@v2
        with:
            # we really need a way for Psalm to tell where cache is located
            path: |
              ~/.cache/psalm
            key: ${{ runner.os }}-psalm-cache-v3-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-psalm-cache-v3-
```
