### ISSUE TITLE
Psalm + BitBucket Pipeline: Could not resolve config path

### ISSUE THREAD

**Issue by paulshryock** [vimeo/psalm#7393]
## Summary
When I run Psalm in a BitBucket Pipeline, it fails to resolve the config path. Psalm runs fine locally.

**Does anyone have experience successfully running Psalm in a BitBucket Pipeline?**

```bash
+ composer analyze
> ./vendor/bin/psalm --config=$(echo $PSALM_CONFIG_PATH) --diff --threads=8
Problem parsing /opt/atlassian/pipelines/agent/build/psalm.xml:
  Could not resolve config path to /opt/atlassian/pipelines/agent/build//
Script ./vendor/bin/psalm --config=$(echo $PSALM_CONFIG_PATH) --diff --threads=8 handling the analyze:code event returned with error code 1
```

<img width="1487" alt="Screenshot of failed BitBucket pipeline" src="https://user-images.githubusercontent.com/7530507/149539850-4106da99-977b-4304-994e-579ed0ae51e9.png">

## Versions

These are my local versions, and I have confirmed that they are identical to what runs in the `composer:latest` image on my BitBucket pipeline.

```bash
$ php --version
PHP 8.1.1 (cli) (built: Dec 17 2021 22:38:05) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.1, Copyright (c), by Zend Technologies

$ composer --version
Composer version 2.2.3 2021-12-31 12:18:53

$ vendor/bin/psalm --version
Psalm v4.15.0@a1b5e489e6fcebe40cb804793d964e99fc347820
```

## My setup
```bash
# Project directory structure
.
├── bitbucket-pipelines.yml
├── composer.json
├── composer.lock
├── psalm.xml
├── .psalm
├── dist
├── src
├── tests
└── vendor
```

```bash
# .env.local
$PSALM_CONFIG_PATH=./psalm.xml
```

```bash
# BitBucket Pipeline Environment Variables
$PSALM_CONFIG_PATH=/opt/atlassian/pipelines/agent/build/psalm.xml
```

```json
// composer.json
{
  "require-dev": {
    "humanmade/psalm-plugin-wordpress": "^2.0",
    "vimeo/psalm": "^4.13"
  },
  "scripts": {
    "analyze": "./vendor/bin/psalm --config=$(echo $PSALM_CONFIG_PATH) --diff --threads=8"
  }
}
```

```xml
<!-- psalm.xml -->
<?xml version="1.0"?>
<psalm
  cacheDirectory=".psalm"
  errorLevel="1"
  resolveFromConfigFile="true"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="https://getpsalm.org/schema/config"
  xsi:schemaLocation="https://getpsalm.org/schema/config vendor/vimeo/psalm/config.xsd"
>
  <projectFiles>
    <directory name="."/>
    <ignoreFiles>
      <directory name=".psalm"/>
      <directory name="dist"/>
      <directory name="tests"/>
      <directory name="vendor"/>
    </ignoreFiles>
  </projectFiles>
  <plugins>
    <pluginClass class="PsalmWordPress\Plugin"/>
  </plugins>
</psalm>
```

```yaml
# bitbucket-pipelines.yml
image: composer:latest

pipelines:
  default:
    - step:
        name: PHP static analysis
        script:
          - composer install
          - composer analyze
        caches:
          - composer
          - psalm

definitions:
  caches:
    psalm: .psalm
```
